name: flutter_store_pickers
description: Customizable Pickers for Products of any Store
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  iconify_flutter: ^0.0.7
  intl: ^0.19.0
  money2: ^5.3.0
  shadcn_ui: ^0.15.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
